name: DAL-Tests
run-name: ${{ github.actor }} is pushed changes with modifications in DAL or TESTS layer. 
on:
  push:
    branches:
      - main
    paths:
      - 'OfferNegotiator/OfferNegotiatorDal/**'
      - 'OfferNegotiator/OfferNegotiatorTests/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./OfferNegotiator/OfferNegotiator.sln
    - name: Build
      run: dotnet build ./OfferNegotiator/OfferNegotiator.sln --no-restore
    - name: Test
      run: dotnet test ./OfferNegotiator/OfferNegotiatorTests/OfferNegotiatorTests.csproj --filter FullyQualifiedName~RepositoriesTests --no-build --verbosity normal
